apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels: 
    app: mongo
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mongo
  template: 
    metadata:
      labels:
        app: mongo
    spec: 
      containers: 
        - name: mongo-express
          image: mongo-express:latest
          ports: 
          - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
            valueFrom: 
              secretKeyRef:
                name: secret
                key: mongo-user
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom: 
              secretKeyRef:
                name: secret
                key: mongo-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: 
              ConfigMapKeyRef:
                name: mongo-config
                key: mongo-url

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-deployment
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30200